CREATE TABLE COLEGIO..ANIO_ESCOLAR(
ANIO INT NOT NULL,
NOMBRE_ESTADO VARCHAR(300) NOT NULL,
NOMBRE_COLEGIO VARCHAR(300) NOT NULL,
FEC_INICIO DATETIME NOT NULL,
FEC_FIN DATETIME NOT NULL
);
GO

USE COLEGIO;
SELECT NAME FROM SYS.tables;
GO

INSERT INTO COLEGIO..ANIO_ESCOLAR(ANIO,NOMBRE_ESTADO,NOMBRE_COLEGIO,FEC_INICIO,FEC_FIN)
VALUES(2023,'NO SE','AÑO DEL DESARROLLO TECNOLOGICO','20230301','20231215');
GO

SELECT * FROM COLEGIO..ANIO_ESCOLAR;
GO

ALTER TABLE COLEGIO..ANIO_ESCOLAR
ADD CONSTRAINT PK_ANIO_ESCOLAR
PRIMARY KEY(ANIO);
GO

SELECT TYPE, NAME
FROM sys.objects
WHERE TYPE='PK';
GO

INSERT INTO COLEGIO..ANIO_ESCOLAR(ANIO,NOMBRE_ESTADO,NOMBRE_COLEGIO,FEC_INICIO,FEC_FIN)
VALUES(2023,'NO SE','AÑO DEL DESARROLLO TECNOLOGICO','20230301','20231215');
GO




