-- BASE DE DATOS
USE ACADEMICO;
GO

-- CURSO

SET IDENTITY_INSERT CURSO ON
GO

INSERT INTO CURSO(CUR_ID,CUR_NOMBRE,CUR_PRECIO,CUR_VACANTES,CUR_MATRICULADOS,CUR_PROFESOR)
VALUES(1,'GDI-1',1000.0,50,0,'GUSTAVO CORONEL');
GO

INSERT INTO CURSO(CUR_ID,CUR_NOMBRE,CUR_PRECIO,CUR_VACANTES,CUR_MATRICULADOS,CUR_PROFESOR)
VALUES(2,'GDI-2',1200.0,50,0,'GUSTAVO CORONEL');
GO

INSERT INTO CURSO(CUR_ID,CUR_NOMBRE,CUR_PRECIO,CUR_VACANTES,CUR_MATRICULADOS,CUR_PROFESOR)
VALUES(3,'JAVA OO',1000.0,50,0,'GUSTAVO CORONEL');
GO

INSERT INTO CURSO(CUR_ID,CUR_NOMBRE,CUR_PRECIO,CUR_VACANTES,CUR_MATRICULADOS,CUR_PROFESOR)
VALUES(4,'SPRING BOOT',1800.0,50,0,'GUSTAVO CORONEL');
GO

INSERT INTO CURSO(CUR_ID,CUR_NOMBRE,CUR_PRECIO,CUR_VACANTES,CUR_MATRICULADOS,CUR_PROFESOR)
VALUES(5,'ORACLE',1800.0,50,0,'GUSTAVO CORONEL');
GO

SET IDENTITY_INSERT CURSO OFF
GO


SELECT * FROM CURSO;
GO


-- ALUMNO

SET IDENTITY_INSERT ALUMNO ON
GO

INSERT INTO ALUMNO(ALU_ID,ALU_NOMBRE,ALU_DIRECCION,ALU_EMAIL,ALU_TELEFONO)
VALUES(1,'LERIDA JARA','LOS OLIVOS','LERIDA@GMAIL.COM','969496923');
GO

INSERT INTO ALUMNO(ALU_ID,ALU_NOMBRE,ALU_DIRECCION,ALU_EMAIL,ALU_TELEFONO)
VALUES(2,'PAMELA VEGA','LOS OLIVOS','PAMELA@GMAIL.COM','975467981');
GO


SET IDENTITY_INSERT ALUMNO OFF
GO


SELECT * FROM ALUMNO;
GO

